# server port
server:
  port: 443
  ssl:
    key-store: classpath:www.dawnfz.com.pfx
    # 本地测试证书的密码 - 无实际作用
    key-store-password: VFd9Jj9J
    key-store-type: pkcs12
  error:
    include-message: always
  servlet:
    context-path: /PotCopy
# spring config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pot_copy?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    druid:
      max-active: 20
      initial-size: 5
      min-idle: 5
      min-evictable-idle-time-millis: 300000
      max-wait: 60000
      validation-query: select 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml
# log[全局异常处理器]
exception:
  log: # log 存放位置
    exLogPath: ./log
# pagehelper config
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# swagger-ui config
springdoc:
  swagger-ui:
    tags-sorter: alpha # 排序方式[按字母]
    enabled: true #生产环境请关闭
  api-docs:
    enabled: true #生产环境请关闭
# 自定义鉴权授权配置
config:
  jwt:
    header: Authorization
    scheme: Bearer
    secret: DawnFz-Love-MiaoPu
    expire: 43200
    role-map:
      0: Manager
      1: Author